name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: ls
      - run:    git rev-parse HEAD
      - run: mvn test-compile -pl . -am
      - run:      mvn -pl . test -Dtest=com.authy.api.UserStatusTest#testToXML
      - run:      mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.authy.api.UserStatusTest#testToXML -DnondexRuns=10
      
